services:
  # L'application AppDAF
  app:
    build: 
      context: .
      dockerfile: .docker/php/Dockerfile
      target: base
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: appdaf_app
    volumes:
      - .:/var/www/html
    environment:
      - APP_URL=http://seck.moustapha.sa.edu.sn:7778
      - DB_HOST=db
      - DB_NAME=tafa
      - DB_USER=postgres
      - DB_PASS=root123
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - appdaf_network

  # Le serveur web NGINX
  nginx:
    image: nginx:alpine
    container_name: appdaf_nginx
    ports:
      - "7778:80" 
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appdaf_network

  # La base de données PostgreSQL
  db:
    image: postgres:15
    container_name: appdaf_db
    environment:
      POSTGRES_DB: tafa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"  # Changé de 5432 à 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appdaf_network

# Les réseaux et volumes
networks:
  appdaf_network:
    driver: bridge

volumes:
  postgres_data: